### ISSUE TITLE
v1.5.0 変更内容

### ISSUE THREAD

**Issue by DKAlpha** [SpriteStudio/SpriteStudio6-SDK#17]
Ver1.5.0の変更内容です。  
- デフォームアトリビュートの対応  
  - SpriteStudio6.2.0で追加されたデフォームアトリビュートが使用できます。  
- マスクが複数重なっている場合に奥のマスクを非表示にすると手前のマスクに影響してしまう問題の修正
- エフェクト、フェードコマンドを0％から開始すると0除算が発生する可能性の対応
- エフェクト、収束点コマンドで0,0を指定すると収束しない問題の修正
- パーツカラー、ミックス、頂点、選択肢時に不透明度が効かない制限の解消
  - SpriteStudio6.0、6.1.3では不透明度がブレンド率（Rate）に反映されていましたが、6.2.0では不透明度として機能し透明にする事ができます。

**Comment by Naruto** [comment]
https://github.com/SpriteStudio/SpriteStudio6-SDK/releases/tag/1.5.0_SS6.2.0 へ引っ越し
