### ISSUE TITLE
Ver1.3.2 5頂点でのスプライト表示に対応しました

### ISSUE THREAD

**Issue by DKAlpha** [SpriteStudio/SpriteStudio6-SDK#7]
SpriteStudio本体は5頂点でのスプライト表示を行っているが、SDKでは4頂点でのスプライト表示を行っている。
このため頂点変形を使用した場合のゆがみ方が本体を違う。

この問題はVer.1.3.2で対応しました。
ssplayer_animedecode.hに適宜されている、USE_TRIANGLE_FINを変更する事で4頂点でのスプライト表示と５頂点でのスプライト表示を切り替える事ができます。
https://github.com/SpriteStudio/SpriteStudio6-SDK/blob/master/Common/Animator/ssplayer_animedecode.h#L21-L24

頂点変形アトリビュートとパーツカラーを使用しているパーツ以外は4頂点でのスプライト表示が行われます。

**Comment by Naruto** [comment]
https://github.com/SpriteStudio/SpriteStudio6-SDK/releases/tag/1.3.2_SS6.1.0 へ引っ越し
